import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Locale, NextIntlClientProvider } from 'next-intl';
import { WipDisclaimer } from '@/shared/components/WipDisclaimer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  locale,
}: Readonly<{
  children: React.ReactNode;
  locale: Locale;
}>) {
  return (
    <NextIntlClientProvider locale={locale as Locale}>
      <html lang='en' className='h-full border-red-500 overflow-hidden'>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-full overflow-auto scroll-smooth`}
        >
          {children}
          <WipDisclaimer className='bottom-32 right-8 z-50 absolute ml-auto block' />
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
